DjangoSalt/DjangoSalt/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import staticfiles

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^salt/', include('salt.urls')),
]
urlpatterns += staticfiles_urlpatterns()

DjangoSalt/salt/urls.py
from django.conf.urls import url
from salt import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/', views.acc_login, name='login'),
    url(r'^logout/', views.acc_logout, name='logout'),
    url(r'^saltstack/', views.saltstack, name='saltstack'),
    url(r'^download/', views.download, name="download"),
    url(r'^switch/', views.nginx_switch, name="switch"),
]

DjangoSalt/salt/forms.py
from django import forms



class UserForm(forms.Form):
    saltClient = forms.CharField(label="client", max_length=50)
    saltParams1 = forms.CharField(label="params1", max_length=100)
    saltParams2 = forms.CharField(label="params2", max_length=100)
class SaltForm(forms.Form):
    Client = forms.CharField(label="client", max_length=50)
    Params = forms.CharField(label="params", max_length=100)

class DownloadForm(forms.Form):
    projectname = forms.CharField(label="projectname", max_length=50)
    filename = forms.CharField(label="filename", max_length=100)

class LogNameForm(forms.Form):
    loglist = forms.CharField(label="loglist", max_length=100)

class SQLListForm(forms.Form):
    sqllist = forms.CharField(label="sqlname", max_length=100)

class SQLNameForm(forms.Form):
    sqlname = forms.CharField(label="sqlname", max_length=100)

DjangoSalt/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block title %}主页{% endblock %}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdn.bootcss.com/ionicons/4.1.2/css/ionicons.min.css">
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  {% block css %}{% endblock %}

</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="#" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini">DS</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>DS平台</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
          <div class="container-fluid">
          <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown user user-menu">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">{{ request.user }}<b class="caret"></b></a>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
                                <li><a href="#">个人信息</a></li>
                                <li><a href="{% url 'logout' %}">Logout</a></li>
                            </ul>
                    </li>
          </ul>
          </div>
      </ul>
      </div>
</nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <!-- search form -->
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu">
        <li class="header">导航栏</li>
        <li class="treeview">
          <a href="/salt/">
            <i class="fa fa-dashboard"></i> <span>首页</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
        </li>
        <li class="treeview">
          <a href="/salt/saltstack/">
            <i class="fa fa-dashboard"></i> <span>远程执行</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
        </li>
        <li class="treeview">
          <a href="/salt/download/">
            <i class="fa fa-table"></i> <span>日志下载</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
        </li>
        <li class="treeview">
          <a href="/salt/switch/">
            <i class="fa fa-table"></i> <span>Nginx切换</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
        </li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">

      {#        主体内容全放到这里！#}
      {% block content %}{% endblock %}

  </div>


</div>
<!-- ./wrapper -->

<!-- jQuery 2.2.3 -->
<script src="{% static 'plugins/jQuery/jquery-2.2.3.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'plugins/jQueryUI/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.6 -->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
{% block script %}{% endblock %}

</body>
</html>

DjangoSalt/templates/download.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}首页{% endblock %}

{% block css %}

<!-- DataTables -->
  <link rel="stylesheet" href="{% static 'plugins/datatables/dataTables.bootstrap.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">

{% endblock %}

{% block content %}
    <section class="content-header">
      <h1>
        日志下载
        <small>gray</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{% url 'index' %}"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li class="active">日志下载</li>
      </ol>
    </section>
    <section class="content">
        <div class="box">
            <main role="main" class="col-sm-3 ml-sm-auto col-md-8 pt-2">
            <br>
            <form class="form-horizontal" role="form" method="POST">
            {% csrf_token %}
                <div class="form-group col-sm-10">
                <label for="id_loglist">项目名称</label>
                <p class="text-info"><strong>{{ list1 }}</strong></p>
                <input type="text" name="loglist" class="form-control" id="loglist" 
                    placeholder="请输入项目名称查看日志文件">
                </div>
            <br>
            <div class="col-sm-8 col-sm-offset-0">
                <button type="submit" class="btn btn-default">确认</button>
            </div>
            </form>
            </main>
    </section>
            <div class="box-body">
            <main role="main" class="col-sm-9 ml-sm-auto col-md-8 pt-3">
            {% if result %}
                <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">文件列表</h3>
                </div>
                <div class="panel-body">
                    <pre><core>{{ info3 }}</core></pre>
                </div>
                </div>
            {% endif %}
            </main>
            </div>
    <section class="content">
            <main role="main" class="col-sm-3 ml-sm-auto col-md-8 pt-2">
            <form class="form-horizontal" role="form" method="POST">
            {% csrf_token %}
                <div class="form-group col-sm-10">
                    <label for="id_projectname">项目名称</label>
                    <p class="text-info"><strong>{{ list1 }}</strong></p>
                    <input type="text" name="projectname" class="form-control" id="projectname"
                        placeholder="请输入项目名称">
                    <br>
                    <label for="id_filename">日志文件</label>
                    <input type="text" name="filename" class="form-control" id="filename"
                        placeholder="请输入日志文件名">
                </div>
                <br>
                <div class="col-sm-8 col-sm-offset-0">
                <button type="submit" class="btn btn-default">提交</button>
                </div>
            </form>
            </main>
    </section>
{% endblock %}
{% block script %}
    <!-- AdminLTE App -->
    <!-- SlimScroll 1.3.0 -->
    <script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js' %}"></script>
    <script src="{% static 'plugins/fastclick/fastclick.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/app.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'dist/js/demo.js' %}"></script>
    <script src="{% static 'plugins/knob/jquery.knob.js' %}"></script>
    <!-- page script -->
{% endblock %}

DjangoSalt/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}首页{% endblock %}

{% block css %}

<!-- DataTables -->
  <link rel="stylesheet" href="{% static 'plugins/datatables/dataTables.bootstrap.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">

{% endblock %}

{% block content %}
     <section class="content-header">
      <h1>
        欢迎回来！
        <small></small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{% url 'index' %}"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li class="active"></li>
      </ol>
    </section>
{% endblock %}
{% block script %}
    <!-- AdminLTE App -->
    <!-- SlimScroll 1.3.0 -->
    <script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js' %}"></script>
    <script src="{% static 'plugins/fastclick/fastclick.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/app.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'dist/js/demo.js' %}"></script>
    <script src="{% static 'plugins/knob/jquery.knob.js' %}"></script>
    <!-- page script -->
{% endblock %}

DjangoSalt/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="zh-CN">
      <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %}登陆界面{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="signin.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>

    <![endif]-->
  </head>
{#templates/login.html#}
{% block extra-css %}
    <link rel="stylesheet" href="https://v3.bootcss.com/examples/signin/signin.css">
{% endblock %}
{% block body %}
 <div class="container">
      <form class="form-signin" method="post">
          {% csrf_token %}
        <h2 class="form-signin-heading">欢迎登陆</h2>
        <label for="inputEmail" class="sr-only">Username</label>
        <input type="text" id="" name="username" class="form-control" placeholder="Username" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password" required>
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>
 </div> <!-- /container -->
        <!-- /container -->
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="http://v3.bootcss.com/assets/js/ie10-viewport-bug-workaround.js"></script>
{% endblock %}
</html>

DjangoSalt/templates/nginx_switch.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}首页{% endblock %}

{% block css %}

<!-- DataTables -->
  <link rel="stylesheet" href="{% static 'plugins/datatables/dataTables.bootstrap.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">
  <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">   

{% endblock %}

{% block content %}
    <section class="content-header">
      <h1>
        Nginx切换
        <small>Online</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{% url 'index' %}"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li class="active">Nginx切换</li>
      </ol>
    </section>
    <section class="content">
        <div class="box">
            <main role="main" class="col-sm-3 ml-sm-auto col-md-8 pt-2">
            <br>
            <form method="post" action="" onsubmit="return">
            {% csrf_token %}
              <div class="btn-group">
              <p>
                <button type="submit" class="btn btn-success btn-lg" name="reload">service nginx reload</button>
              </p>
              <h3>dy</h3>
              <p>
	        <button type="submit" class="btn btn-primary btn-lg" name="1">切换 1</button>
                <button type="submit" class="btn btn-info btn-lg" name="2">切换 2</button>
	        <button type="submit" class="btn btn-warning btn-lg" name="3">切换 3</button>
              </p>
              <h3>yoya</h3>
              <p>
                <button type="submit" class="btn btn-primary btn-lg" name="4">切换 1</button>
                <button type="submit" class="btn btn-info btn-lg" name="5">切换 2</button>
                <button type="submit" class="btn btn-warning btn-lg" name="6">切换 3</button>
              </p>
              <h3>all</h3>
              <p>
                <button type="submit" class="btn btn-primary btn-lg" name="7">切换 1</button>
                <button type="submit" class="btn btn-info btn-lg" name="8">切换 2</button>
                <button type="submit" class="btn btn-warning btn-lg" name="9">切换 3</button>
              </p>
              </div>
              <br>
        </div>
    </section>
        <div class="box-body">
            <main role="main" class="col-sm-3 ml-sm-auto col-md-8 pt-2">
            {% if result %}
              <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">执行结果</h3>
                </div>
                <div class="panel-body">
                    <pre><core>{{ info }}</core></pre>
                </div>
                </div>
            {% endif %}
            </main>
        </div>
{% endblock %}
{% block script %}
    <!-- AdminLTE App -->
    <!-- SlimScroll 1.3.0 -->
    <script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js' %}"></script>
    <script src="{% static 'plugins/fastclick/fastclick.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/app.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'dist/js/demo.js' %}"></script>
    <script src="{% static 'plugins/knob/jquery.knob.js' %}"></script>
    <!-- page script -->
{% endblock %}

DjangoSalt/templates/salt_page.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}首页{% endblock %}

{% block css %}

<!-- DataTables -->
  <link rel="stylesheet" href="{% static 'plugins/datatables/dataTables.bootstrap.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">

{% endblock %}

{% block content %}
    <section class="content-header">
      <h1>
        远程执行
        <small>gray</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{% url 'index' %}"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li class="active">远程执行</li>
      </ol>
    </section>
    <section class="content">
        <div class="box">
            <main role="main" class="col-sm-3 ml-sm-auto col-md-8 pt-2">
            <form class="form-horizontal" role="form" method="POST">
            {% csrf_token %}
                <div class="form-group col-sm-10">
                    <br>
                    <p class="text-warning">灰度更新</p>
                    <label for="id_saltClient">主机名</label>
                    <select class="form-control" name="saltClient" id="saltClient">
                        <option>yoya-test-app</option>
                        <option>gray-onemovi</option>
			<option>gray-dy-app</option>
                    </select>
                    <br>
                    <label for="id_saltParams1">params1
                    <input type="text" name="saltParams1" class="form-control" id="saltParams1"
                        placeholder="格式：日期+数字">
                    </label>
                    (目录名称)
                    <label for="id_saltParams2">params2
                    <input type="text" name="saltParams2" class="form-control" id="saltParams2"
                        placeholder="格式：xxx.zip">
                    </label>
                    (文件名称)
                </div>
                <div class="col-sm-8 col-sm-offset-0">
                <button type="submit" class="btn btn-default">确认</button>
                </div>
            </form>
            </main>
        </div>
    </section>
        <div class="box-body">
            <main role="main" class="col-sm-9 ml-sm-auto col-md-8 pt-3">
            {% if result %}
                <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">执行结果</h3>
                </div>
                <div class="panel-body">
                    <pre><core>{{ info2 }}</core></pre>
                </div>
                </div>
            {% endif %}
            </main>
        </div>
    <section class="content">
        <div class="box">
            <main role="main" class="col-sm-3 ml-sm-auto col-md-8 pt-2">
            <form class="form-horizontal" role="form" method="POST">
            {% csrf_token %}
                <div class="form-group col-sm-10">
                    <br>
                    <p class="text-info">远程执行</p>
                    <label for="id_Client">主机名</label>
                    <select class="form-control" name="Client" id="Client">
                        <option>yoya-test-app</option>
                        <option>gray-onemovi</option>
                        <option>gray-dy-app</option>
                    </select>
                    <br>
                    <label for="id_Params">指令</label>
                    <input type="text" name="Params" class="form-control" id="Params"
                        placeholder="请输入指令">
                </div>
                <div class="col-sm-8 col-sm-offset-0">
                <button type="submit" class="btn btn-default">确认</button>
                </div>
            </form>
            </main>
        </div>
    </section>
        <div class="box-body">
            <main role="main" class="col-sm-9 ml-sm-auto col-md-8 pt-3">
            {% if result %}
                <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">执行结果</h3>
                </div>
                <div class="panel-body">
                    <pre><core>{{ info3 }}</core></pre>
                </div>
                </div>
            {% endif %}
            </main>
        </div>
{% endblock %}
{% block script %}
    <!-- AdminLTE App -->
    <!-- SlimScroll 1.3.0 -->
    <script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js' %}"></script>
    <script src="{% static 'plugins/fastclick/fastclick.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/app.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'dist/js/demo.js' %}"></script>
    <script src="{% static 'plugins/knob/jquery.knob.js' %}"></script>
    <!-- page script -->
{% endblock %}