DjangoSalt/DjangoSalt/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import staticfiles

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^salt/', include('salt.urls')),
]
urlpatterns += staticfiles_urlpatterns()

DjangoSalt/salt/urls.py
from django.conf.urls import url
from salt import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/', views.acc_login, name='login'),
    url(r'^logout/', views.acc_logout, name='logout'),
    url(r'^saltstack/', views.saltstack, name='saltstack'),
    url(r'^download/', views.download, name="download"),
    url(r'^switch/', views.nginx_switch, name="switch"),
]

salt/forms.py
from django import forms



class UserForm(forms.Form):
    saltClient = forms.CharField(label="client", max_length=50)
    saltParams = forms.CharField(label="params", max_length=100)

class DownloadForm(forms.Form):
    projectname = forms.CharField(label="projectname", max_length=50)
    filename = forms.CharField(label="filename", max_length=100)

class LogNameForm(forms.Form):
    loglist = forms.CharField(label="loglist", max_length=100)

class SQLListForm(forms.Form):
    sqllist = forms.CharField(label="sqlname", max_length=100)

class SQLNameForm(forms.Form):
    sqlname = forms.CharField(label="sqlname", max_length=100)

templates/download.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}首页{% endblock %}

{% block css %}

<!-- DataTables -->
  <link rel="stylesheet" href="{% static 'plugins/datatables/dataTables.bootstrap.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">

{% endblock %}

{% block content %}
    <section class="content-header">
      <h1>
        日志下载
        <small>gray</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{% url 'index' %}"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li class="active">日志下载</li>
      </ol>
    </section>
    <section class="content">
        <div class="box">
            <main role="main" class="col-sm-3 ml-sm-auto col-md-8 pt-2">
            <br>
            <form class="form-horizontal" role="form" method="POST">
            {% csrf_token %}
                <div class="form-group col-sm-10">
                <label for="id_loglist">项目名称</label>
                <input type="text" name="loglist" class="form-control" id="loglist" 
                    placeholder="请输入项目名称查看日志文件">
                </div>
            <br>
            <div class="col-sm-8 col-sm-offset-0">
                <button type="submit" class="btn btn-default">确认</button>
            </div>
            </form>
            </main>
    </section>
            <div class="box-body">
            <main role="main" class="col-sm-9 ml-sm-auto col-md-8 pt-3">
            {% if result %}
                <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">文件列表</h3>
                </div>
                <div class="panel-body">
                    <pre><core>{{ info3 }}</core></pre>
                </div>
                </div>
            {% endif %}
            </main>
            </div>
    <section class="content">
            <main role="main" class="col-sm-3 ml-sm-auto col-md-8 pt-2">
            <form class="form-horizontal" role="form" method="POST">
            {% csrf_token %}
                <div class="form-group col-sm-10">
                    <label for="id_projectname">项目名称</label>
                    <input type="text" name="projectname" class="form-control" id="projectname"
                        placeholder="请输入项目名称">
                    <br>
                    <label for="id_filename">日志文件</label>
                    <input type="text" name="filename" class="form-control" id="filename"
                        placeholder="请输入日志文件名">
                </div>
                <br>
                <div class="col-sm-8 col-sm-offset-0">
                <button type="submit" class="btn btn-default">提交</button>
                </div>
            </form>
            </main>
    </section>
{% endblock %}
{% block script %}
    <!-- AdminLTE App -->
    <!-- SlimScroll 1.3.0 -->
    <script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js' %}"></script>
    <script src="{% static 'plugins/fastclick/fastclick.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/app.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'dist/js/demo.js' %}"></script>
    <script src="{% static 'plugins/knob/jquery.knob.js' %}"></script>
    <!-- page script -->
{% endblock %}

templates/salt_page.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}首页{% endblock %}

{% block css %}

<!-- DataTables -->
  <link rel="stylesheet" href="{% static 'plugins/datatables/dataTables.bootstrap.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">

{% endblock %}

{% block content %}
    <section class="content-header">
      <h1>
        远程执行
        <small>gray</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{% url 'index' %}"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li class="active">远程执行</li>
      </ol>
    </section>
    <section class="content">
        <div class="box">
            <main role="main" class="col-sm-3 ml-sm-auto col-md-8 pt-2">
            <form class="form-horizontal" role="form" method="POST">
            {% csrf_token %}
                <div class="form-group col-sm-10">
                    <br>
                    <label for="id_saltClient">主机名</label>
                    <select class="form-control" name="saltClient" id="saltClient">
                        <option>yoya-test-app</option>
                        <option>gray-onemovi</option>
			<option>gray-dy-app</option>
                    </select>
                    <br>
                    <label for="id_saltParams">指令</label>
                    <input type="text" name="saltParams" class="form-control" id="saltParams"
                        placeholder="请输入指令">
                </div>
                <div class="col-sm-8 col-sm-offset-0">
                <button type="submit" class="btn btn-default">确认</button>
                </div>
            </form>
            </main>
        </div>
    </section>
        <div class="box-body">
            <main role="main" class="col-sm-9 ml-sm-auto col-md-8 pt-3">
            {% if result %}
                <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">执行结果</h3>
                </div>
                <div class="panel-body">
                    <pre><core>{{ info2 }}</core></pre>
                </div>
                </div>
            {% endif %}
            </main>
        </div>
{% endblock %}
{% block script %}
    <!-- AdminLTE App -->
    <!-- SlimScroll 1.3.0 -->
    <script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js' %}"></script>
    <script src="{% static 'plugins/fastclick/fastclick.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/app.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'dist/js/demo.js' %}"></script>
    <script src="{% static 'plugins/knob/jquery.knob.js' %}"></script>
    <!-- page script -->
{% endblock %}